name: Spell Check

on:
  pull_request:
    branches: [main]
    paths: ['*.md', '**/*.md']

permissions:
  contents: read
  pull-requests: write

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: .git,node_modules,package-lock.json
          ignore_words_list: alot,optin,optout,teh,ba,bu,ist,ons,ot,paralel,ro,ser,sur,ue
          only_warn: 1
